# Generated by Django 4.2 on 2023-04-14 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PersonalInformation",
            fields=[
                ("SEQN", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=250)),
                ("Gender", models.IntegerField(max_length=10)),
                ("Age", models.FloatField()),
                ("Race", models.CharField(blank=True, max_length=30, null=True)),
                ("Height", models.FloatField(blank=True, null=True)),
                ("Weight", models.FloatField()),
                ("Bmi", models.FloatField()),
                ("Email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone_number", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MedicalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "DiabetesPedigree",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("PCOD", models.CharField(blank=True, max_length=10, null=True)),
                ("Pregnancy", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "Hypertension",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "SEQN",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Diabetes.personalinformation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lifestyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "SmokingStatus",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("DietIntake", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "AlcoholConsumption",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("ActivityLevel", models.IntegerField()),
                ("SleepDuration", models.IntegerField(blank=True, null=True)),
                (
                    "SEQN",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Diabetes.personalinformation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabReports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Diabetes_Status",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("HbA1c", models.FloatField(blank=True, null=True)),
                ("Glucose", models.FloatField(blank=True, null=True)),
                ("cholesteral", models.FloatField()),
                ("Triglycerides", models.FloatField()),
                ("Blood_Pressure_Systolic", models.FloatField(blank=True, null=True)),
                ("Blood_Pressure_Diastolic", models.FloatField(blank=True, null=True)),
                (
                    "SEQN",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Diabetes.personalinformation",
                    ),
                ),
            ],
        ),
    ]
