# Generated by Django 4.2 on 2023-04-14 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Diabetes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="labreports",
            old_name="cholesteral",
            new_name="cholesterol",
        ),
    ]
