# Generated by Django 4.2 on 2023-04-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Diabetes", "0002_rename_cholesteral_labreports_cholesterol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lifestyle",
            name="DietIntake",
        ),
        migrations.RemoveField(
            model_name="medicalhistory",
            name="Hypertension",
        ),
        migrations.AlterField(
            model_name="labreports",
            name="Diabetes_Status",
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="lifestyle",
            name="ActivityLevel",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="lifestyle",
            name="AlcoholConsumption",
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="lifestyle",
            name="SmokingStatus",
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="DiabetesPedigree",
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="PCOD",
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="Pregnancy",
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="Age",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="Race",
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
    ]
