# Generated by Django 4.2 on 2023-04-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Diabetes", "0003_remove_lifestyle_dietintake_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="demographic_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
            ],
        ),
    ]
