# Generated by Django 4.2 on 2023-04-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Diabetes", "0004_demographic_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="demographic_data",
            name="year_2000",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="demographic_data",
            name="year_2011",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="demographic_data",
            name="year_2021",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="demographic_data",
            name="year_2030",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="demographic_data",
            name="year_2045",
            field=models.FloatField(default=0),
        ),
    ]
